# DigitalOcean App Platform Configuration
name: jordan-cowan-portfolio
services:
- name: web
  source_dir: /
  github:
    repo: your-username/portfolio
    branch: main
  run_command: npm start
  build_command: npm run build
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  static_sites:
  - name: frontend
    source_dir: /dist
    index_document: index.html
    error_document: index.html
    routes:
    - path: /
