name: CI/CD Pipeline

on:
  # Trigger on pushes to main branch
  push:
    branches: [ main ]
  # Trigger on pull requests to main branch
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Schedule security audit weekly (Sundays at 2 AM UTC)
  schedule:
    - cron: '0 2 * * 0'

# Set permissions for GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job 1: Quality Checks & Testing
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: TypeScript Check
        run: npx tsc --noEmit
        
      - name: Code Quality (Biome)
        run: npm run lint
        
      - name: Build Test
        run: npm run build
        
      - name: Bundle Size Check (Informational)
        run: |
          echo "Build completed successfully!"
          if [ -d "dist" ]; then
            echo "Bundle size information:"
            du -sh dist/
            find dist -name "*.js" -o -name "*.css" | head -10 | xargs ls -lh
          fi

  # Job 2: Build & Deploy (only on main branch)
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Production
        run: npm run build
        env:
          # Include environment variables for build if needed
          NODE_ENV: production
          
      - name: Build Success
        run: |
          echo "Production build completed successfully!"
          echo "Build artifacts ready for deployment"
          echo "Vercel will automatically deploy this build"

  # Job 3: Security Audit (runs weekly)
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Security Audit
        run: npm audit --audit-level=moderate
        
      - name: Dependency Check
        run: |
          echo "Checking for outdated dependencies..."
          npm outdated || true

# Note: Security audit is also scheduled to run weekly (Sundays at 2 AM UTC)
# This is handled in the main 'on' section above
